# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://wpquickimage.com
title: WP Quick Image
email: ross@oikos.digital
author: Ross Wintle
description: > # "A WordPress plugin for quick posting of images to your blog."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/rosswintle/wp-quick-image
  - title: linkedin
    url: 
